/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XdMERukkLB3
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container flex flex-col items-center justify-center gap-4 px-4 md:px-6">
        <div className="grid gap-4 lg:gap-8 lg:grid-cols-[1fr_600px]">
          <div className="flex flex-col gap-4 lg:gap-8">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter lg:text-6xl xl:text-7xl 2xl:text-8xl">
                Create stunning videos.
              </h1>
              <p className="max-w-[500px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Enter your text and let us handle the rest. Perfect for captions, quotes, and more.
              </p>
            </div>
            <div className="flex flex-col gap-2 min-[400px]:flex-row">
              <Input className="w-full max-w-[400px] justify-start" placeholder="Enter your text" type="email" />
              <Button className="h-10 w-full max-w-xs ml-auto" variant="outline">
                Generate
              </Button>
            </div>
          </div>
          <div className="w-full max-w-[400px] aspect-video rounded-lg overflow-hidden shadow-md" />
        </div>
      </div>
    </section>
  )
}
