/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wgI3xJGuuns
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    <div className="relative flex items-center min-h-[400px] py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container grid items-center gap-6 px-4 md:px-6 lg:gap-12 lg:grid-cols-[1fr_500px] xl:grid-cols-[1fr_600px]">
        <div className="space-y-4">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl">Create short videos</h1>
            <p className="max-w-[400px] text-gray-500 md:text-base/relaxed lg:text-sm/relaxed xl:text-base/relaxed dark:text-gray-400">
              Enter your text and create engaging videos for social media platforms with our AI-powered video generator.
            </p>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <Input className="w-full max-w-[300px] flex-1 text-base" placeholder="Enter your text" type="text" />
            <Button className="h-11" size="lg" variant="outline">
              Generate
            </Button>
          </div>
        </div>
        <div className="w-full aspect-video overflow-hidden rounded-xl border border-gray-200 dark:border-gray-800 dark:border-gray-800">
          <div className="rounded-xl object-cover object-center" />
        </div>
      </div>
      <div className="hidden w-full max-w-7xl absolute inset-0 items-center justify-center md:grid lg:hidden">
        <div />
      </div>
    </div>
  )
}
